---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/authors/{author_id}/articles":
    parameters:
    - name: author_id
      in: path
      description: author_id
      required: true
      schema:
        type: string
    get:
      summary: list articles
      tags:
      - Article
      responses:
        '200':
          description: successful
    post:
      summary: create article
      tags:
      - Article
      parameters: []
      responses:
        '201':
          description: article created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
              required:
              - title
              - body
  "/api/v1/authors/{author_id}/articles/{id}":
    parameters:
    - name: author_id
      in: path
      description: author_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show article
      tags:
      - Article
      responses:
        '200':
          description: successful
    patch:
      summary: update article
      tags:
      - Article
      responses:
        '200':
          description: successful
    put:
      summary: update article
      tags:
      - Article
      responses:
        '200':
          description: successful
    delete:
      summary: delete article
      tags:
      - Article
      responses:
        '200':
          description: successful
  "/api/v1/authors/{author_id}/comments":
    parameters:
    - name: author_id
      in: path
      description: author_id
      required: true
      schema:
        type: string
    get:
      summary: list comments
      tags:
      - Comment
      responses:
        '200':
          description: successful
    post:
      summary: create comment
      tags:
      - Comment
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
                status:
                  type: integer
                article_id:
                  type: integer
              required:
              - article_id
              - body
  "/api/v1/authors/{author_id}/comments/{id}":
    parameters:
    - name: author_id
      in: path
      description: author_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show comment
      tags:
      - Comment
      responses:
        '200':
          description: successful
    patch:
      summary: update comment
      tags:
      - Comment
      responses:
        '200':
          description: successful
    put:
      summary: update comment
      tags:
      - Comment
      responses:
        '200':
          description: successful
    delete:
      summary: delete comment
      tags:
      - Comment
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
